
// Generated by https://quicktype.io

import { DevisStatus } from 'app/core/enums/devis-status.enum';
import { DevisType } from 'app/core/enums/devis-type.enum';
import { FactureType } from 'app/core/enums/facture-type.enum';
import { IAgence } from '../agences/agence.model';
import { IClient, IClientListModel } from '../clients/client.model';
import { IDossier } from '../dossier/dossier.model';
import { IFactureDevis } from '../facture/facture.model';
import { IUserLiteModel } from '../users/user.model';
import { IDocumentAssociate } from 'app/core/models/general/documentAssociate.model';
import { IMailHistoryModel } from 'app/core/models/general/mail.model';
import { IHistorique } from 'app/core/models/general/historique';
import { IArticle } from 'app/core/models/general/article.model';
import { Address } from 'app/core/models/general/address.model';
import { RemiseType } from 'app/core/enums/remise-type.enum';

/**
 * an interface describe devis entity
 */
export interface IDevis {

    /** the id of devis */
    id: string;

    /** the status of devis */
    status: DevisStatus;

    /** the reference of devis */
    reference: string;

    /**  the date of created of dossier */
    createdOn: Date;

    /** the address of intervention devis */
    siteIntervention: Address;

    /** date visit of devis */
    dateVisit: string;

    /** date de creation of devis */
    dateCreation: string;

    /** date visit prealable of devis */
    dateVisitePrealable: string;

    /** list of articles */
    articles: IArticle[];

    /** the type of devis */
    type: DevisType;

    /** the total ht of devis */
    totalHT: number;

    /** the total ttc of devis */
    totalTTC: number;

    /** the remise of devis */
    remise: number;

    /** the remise type of devis */
    remiseType: RemiseType;

    /** the total reduction of devis  */
    totalReduction: number;

    /** the total to paid of devis */
    totalPaid: number;

    /** the date of signature of devis */
    dateSignature: Date;

    /** the signature of devis */
    signe: string;

    /** the name of client who sign devis */
    nameClientSignature: string;

    /** the note of devis */
    note: string;

    /** the note of devis */
    raisonPerdue: string;

    /** the historique of devis */
    historique: IHistorique[];

    /** the list of email in format JSON */
    emails: IMailHistoryModel[];

    /** the technicien id who do the devis */
    userId: string;

    /** the user who do the devis */
    user: IUserLiteModel;

    /** the client id associate with devis */
    clientId: string;

    /** the client associate with devis */
    client: IClient;

    /** the dossier id associate with devis */
    dossierId?: string;

    /** the dossier id associate with devis */
    dossier: IDossier;

    /** the agence associate with devis */
    agence: IAgence;

    /** the agence id associate with devis */
    agenceId: string;

    /** the facture associate with devis */
    factures: IFactureDevis[];

    /** the list of devis associate with this facture */
    documentAssociates: IDocumentAssociate[];

    /** the id of bon commande associate */
    bonCommandeId?: string;

    /* prime cee of dossier */
    primeCEE: IClientListModel;
}

/**
 * an interface describe devis model
 */
export interface IDevisModel {

    /** the reference of devis */
    reference: string;

    /**  the date of created of dossier */
    CreatedOn: Date;

    /** the address of intervention devis */
    siteIntervention: Address;

    /** date visit of devis */
    dateVisit: string;

    /** date de creation of devis */
    dateCreation: string;

    /** date visit prealable of devis */
    dateVisitePrealable: string;

    /** the date of signature of devis */
    dateSignature: Date;

    /** the remise of devis */
    remise: number;

    /** the remise type of devis */
    remiseType: RemiseType;

    /** list of articles */
    articles: IArticle[];

    /** the status of devis */
    status: DevisStatus;

    /** the type of devis */
    type: DevisType;

    /** the total ht of devis */
    totalHT: number;

    /** the total ttc of devis */
    totalTTC: number;

    /** the total reduction of devis  */
    totalReduction: number;

    /** the total to paid of devis */
    totalPaid: number;

    /** the note of devis */
    note: string;

    /** the technicien id who do the devis */
    userId: string;

    /** the client id associate with devis */
    clientId: string;

    /** the dossier id associate with devis */
    dossierId: string;

    /** the agence id associate with devis */
    agenceId: string;

    /** the facture associate with devis */
    factures: IFactureDevis[];

    /** the id of bon commande associate */
    bonCommandeId?: string;
}

/**
 * an interface describe devis dataTable
 */
export interface IDevisDataTables {

    /** the id of devis */
    id: string;

    /** the reference of devis */
    reference: string;

    /** date visit of devis */
    dateVisit: string;

    /** the status of devis */
    status: DevisStatus;

    /** the client id associate with devis */
    clientId: string;

    /** the type of devis */
    type: string;

    /** can modify devis */
    canModify: boolean;

    /** nouvau avancement devis facture */
    nouveauAvancementPercent: number;
}

/**
 * a class decribe data facture devis to transfer devis to an facture
 */
export class IFactureDevisData {

    /**
     * the numero AH
     */
    numeroAH: string;

    /**
     * the type of facture
     */
    type: FactureType;

    /**
     * facture devis information
     */
    factureDevis: IFactureDevis
}
